version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - reports_vol:/app/generated_reports
    environment:
      - GOOGLE_SHEETS_CREDS_JSON=${GOOGLE_SHEETS_CREDS_JSON}
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  reports_vol:
